name: Update Plugins-dev

on:
  push:
    branches: [ master ]
  workflow_dispatch:

# Checks if any concurrent jobs is already being executed for master and cancel it.
concurrency:
  group: ci-master
  cancel-in-progress: true

jobs:
  build-plugins-dev:
    uses: falcosecurity/plugins/.github/workflows/reusable_build_packages.yaml@master
    with:
      makecommand: make packages
      suffix: dev
    secrets: inherit
    
  publish-plugins-dev:
    needs: build-plugins-dev
    uses: falcosecurity/plugins/.github/workflows/reusable_publish_packages.yaml@master
    with:
      suffix: dev
    secrets: inherit  

