name: Update Plugins-dev

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
  workflow_dispatch:

# Checks if any concurrent jobs under the same pull request or branch are being executed
# NOTE: this will cancel every workflow that is being ran against a PR as group is just the github ref (without the workflow name)
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true  
  
permissions:
  id-token: write
  contents: read

env:
  AWS_S3_BUCKET: falco-distribution
  AWS_S3_PREFIX: plugins
  AWS_S3_REGION: eu-west-1

jobs:
  release-plugins-dev-x86:
    runs-on: ubuntu-latest
    container: golang:1.18
    steps:
      - name: Install deps
        run: |
          apt update
          apt install -y --no-install-recommends git awscli
    
      - name: Checkout Plugins ⤵️
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Safe directory
        run: git config --global --add safe.directory $GITHUB_WORKSPACE
          
      - name: Run x86 build 🏗️
        run: make packages

      - name: Configure AWS credentials 🔧⚙️
        if: github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: "arn:aws:iam::292999226676:role/github_actions-plugins-s3"
          aws-region: ${{ env.AWS_S3_REGION }}

      - name: Upload files to S3 ⬆️
        if: github.event_name == 'push'
        run: |
          for package in output/*.tar.gz; do
            aws s3 cp --no-progress $package s3://${{ env.AWS_S3_BUCKET}}/${{ env.AWS_S3_PREFIX }}/dev/
          done

  release-plugins-dev-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Plugins ⤵️
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run arm64 build 🏗️
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu_latest
          githubToken: ${{ github.token }}

          setup: |
            mkdir -p "${PWD}/artifacts"

          dockerRunArgs:
            --volume "${PWD}/artifacts:/artifacts"
            --volume "/var/run/docker.sock:/var/run/docker.sock"
 
          install: |
            apt-get update && apt-get install -y --no-install-recommends docker.io && apt-get clean
            
          run: |
            cat > script.sh <<EOF
            #!/bin/sh
            apt-get update && apt-get install -y --no-install-recommends ca-certificates curl && apt-get clean
            update-ca-certificates
            git config --global --add safe.directory /repo
            cd /repo && make packages
            cp -R output/* /artifacts
            EOF
            chmod +x script.sh
            docker run -ti --rm --platform arm64 -v /artifacts:/artifacts -v ${{ github.workspace }}:/repo golang:1.18 /repo/script.sh

      - name: Configure AWS credentials 🔧⚙️
        if: github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: "arn:aws:iam::292999226676:role/github_actions-plugins-s3"
          aws-region: ${{ env.AWS_S3_REGION }}

      - name: Upload files to S3 ⬆️
        if: github.event_name == 'push'
        run: |
          for package in artifacts/*.tar.gz; do
            aws s3 cp --no-progress $package s3://${{ env.AWS_S3_BUCKET}}/${{ env.AWS_S3_PREFIX }}/dev/
          done
